---
title: "git_00"
author: "Luz Vargas"
date: "9/21/22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

Twinkle, twinkle, little bat!  
How I wonder what you're at!  

Up above the world you fly,  
Like a tea tray in the sky.  

Twinkle, twinkle, little bat!  


## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

The buzz saw snarled and rattled in the yard  
And made dust and dropped stove-length sticks of wood,  
Sweet-scented stuff when the breeze drew across it.  
And from there those that lifted eyes could count  
Five mountain ranges one behind the other  


## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->


"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  

The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

She walks in beauty, like the night  
Of cloudless climes and starry skies;  
And all that’s best of dark and bright  
Meet in her aspect and her eyes;  
Thus mellowed to that tender light  
Which heaven to gaudy day denies.  

One shade the more, one ray the less,  
Had half impaired the nameless grace  
Which waves in every raven tress,  
Or softly lightens o’er her face;  
Where thoughts serenely sweet express,  
How pure, how dear their dwelling-place.  

And on that cheek, and o’er that brow,  
So soft, so calm, yet eloquent,  
The smiles that win, the tints that glow,  
But tell of days in goodness spent,  
A mind at peace with all below,  
A heart whose love is innocent!  

